### ISSUE TITLE
installing VAST

### ISSUE THREAD

**Issue by EllenY** [James-Thorson-NOAA/VAST#297] opened 2021-04-05 22:11 UTC
Hi,
I am having an issue installing the VAST package.

After successfully removing, downloading, and reinstalling Matrix 1.2-17.tar.gz, TMBhelper.zip, TMB-master.zip, INLA_18.07_112.zip, and FishSTatsUtils-development.zip I am getting this error when trying to install VAST-dev.zip

Here is the error:

 remotes::install_local("C:\\Users\\ellen.yasumiishi.vm\\Desktop\\VAST-dev.zip",dep=FALSE, lib="C:/Program Files/Microsoft/R Open/R-3.5.3/library")

ERROR: dependencies 'effects', 'SpatialDeltaGLMM' are not available for package 'VAST'

* removing 'C:/Program Files/Microsoft/R Open/R-3.5.3/library/VAST'
In R CMD INSTALL
Error in i.p(...) :
  (converted from warning) installation of package ‘C:/Users/ELLENY~1.VM/AppData/Local/Temp/3/RtmpEHDOhi/remotes2dc06d537b1f/VAST-dev’ had non-zero exit status

Any insight is much appreciated. Thank you!
EY

**Comment by James-Thorson-NOAA** [comment] 2021-04-05 22:13
Thanks for flagging this!

`SpatialDeltaGLMM` you could install [here](https://github.com/nwfscassess/geostatistical_delta-GLMM/) and that will eliminate that issue.  could you try running `install.packages("effects")` and report whether that eliminates the other issue?

**Comment by EllenY** [comment] 2021-04-05 22:26
Successfully installed effects and SpatialDeltaGLMM, but still not successful in installing VAST
and got the following error.

> remotes::install_local("C:\\Users\\ellen.yasumiishi.vm\\Desktop\\VAST-dev.zip",dep=FALSE, lib="C:/Program Files/Microsoft/R Open/R-3.5.3/library")
* installing *source* package 'VAST' ...
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded
Warning: S3 method 'effects::Effect.fit_model' was declared in NAMESPACE but not found
Downloading GitHub repo james-thorson/FishStatsUtils@2.9.1
Error: package or namespace load failed for 'VAST':
 .onAttach failed in attachNamespace() for 'VAST', details:
  call: utils::download.file(url, path, method = download_method(), quiet = quiet, 
  error: cannot open URL 'https://api.github.com/repos/james-thorson/FishStatsUtils/tarball/2.9.1'
Error: loading failed
Execution halted
ERROR: loading failed
* removing 'C:/Program Files/Microsoft/R Open/R-3.5.3/library/VAST'
In R CMD INSTALL
Error in i.p(...) : 
  (converted from warning) installation of package ‘C:/Users/ELLENY~1.VM/AppData/Local/Temp/3/RtmpQF7oDZ/remotes295827cde2/VAST-dev’ had non-zero exit status
>

**Comment by EllenY** [comment] 2021-04-06 01:09
I had installed an older version of FishStatsUtils 2.9.0, so downloaded the latest development verions v 2.9.1. Then VAST was installed with a minor warning message.
* installing *source* package 'VAST' ...
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded
Warning: S3 method 'effects::Effect.fit_model' was declared in NAMESPACE but not found
* DONE (VAST)
In R CMD INSTALL

Thank you!

**Comment by James-Thorson-NOAA** [comment] 2021-04-06 02:03
Great!  Feel free to keep discussing here, but closing the thread as it seems to be resolved.

**Comment by EllenY** [comment] 2021-04-06 02:54
In working out the Visualize Covariate Response example on the sockeye
data. There's an error.

### Writing output from `fit_model` in directory:
C:/Users/ellen.yasumiishi.vm/Documents/2020/2020Sockeye/

### Making extrapolation-grid
For the UTM conversion, automatically detected zone 3.

### Making spatial information
Loaded from
C:/Users/ellen.yasumiishi.vm/Documents/2020/2020Sockeye//Kmeans-50.RData

### Making data object
Error in FishStatsUtils::make_covariates(formula = X1_formula,
covariate_data = covariate_data,  :
  unused argument (contrasts.arg = X_contrasts)

 Thoughts?


Ellen Yasumiishi, PhD (she/her/hers)
Research Fishery Biologist: 907-209-2819
NOAA Alaska Fisheries Science Center
17109 Point Lena Loop Road, Juneau, AK  99801

**Comment by James-Thorson-NOAA** [comment] 2021-04-06 02:58
after loading VAST what do you get when you run `sessionInfo()`?

**Comment by EllenY** [comment] 2021-04-06 03:02
sessionInfo()
R version 3.5.3 (2019-03-11)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19041)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United
States.1252
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C

[5] LC_TIME=English_United States.1252

attached base packages:
[1] grid      stats     graphics  grDevices utils     datasets  methods
[8] base

other attached packages:
 [1] plotrix_3.7-5          viridis_0.5.1          viridisLite_0.3.0
 [4] magrittr_1.5           dplyr_0.8.0.1          VAST_3.7.1
 [7] TMB_1.7.18             TMBhelper_1.2.0        reshape2_1.4.3
[10] gridExtra_2.3          gridBase_0.4-7         ggplot2_3.1.1
[13] car_3.0-2              akima_0.6-2            mapdata_2.3.0
[16] fields_9.6             maps_3.3.0             spam_2.2-2
[19] dotCall64_1.0-0        SpatialDeltaGLMM_3.6.0 effects_4.1-0
[22] carData_3.0-2          FishStatsUtils_2.9.1   INLA_18.07.12
[25] sp_1.3-1               Matrix_1.2-17          remotes_2.0.4
[28] usethis_1.5.0          devtools_2.0.2         RevoUtils_11.0.3
[31] RevoUtilsMath_11.0.0

loaded via a namespace (and not attached):
 [1] nlme_3.1-137            fs_1.2.7                sf_0.7-3
 [4] rprojroot_1.3-2         tools_3.5.3             backports_1.1.4
 [7] rgdal_1.4-3             R6_2.4.0                DBI_1.0.0
[10] lazyeval_0.2.2          colorspace_1.4-1        nnet_7.3-12
[13] withr_2.1.2             rnaturalearthdata_0.1.0 splancs_2.01-40
[16] tidyselect_0.2.5        prettyunits_1.0.2       processx_3.3.0
[19] curl_3.3                compiler_3.5.3          cli_1.1.0
[22] desc_1.2.0              scales_1.0.0            classInt_0.3-1
[25] callr_3.2.0             stringr_1.4.0           digest_0.6.18
[28] foreign_0.8-71          minqa_1.2.4             rio_0.5.16
[31] pkgconfig_2.0.2         lme4_1.1-21             sessioninfo_1.1.1
[34] rlang_0.3.4             readxl_1.3.1            zip_2.0.1
[37] Rcpp_1.0.1              munsell_0.5.0           abind_1.4-5
[40] stringi_1.4.3           MASS_7.3-51.1           pkgbuild_1.0.3
[43] plyr_1.8.4              forcats_0.4.0           crayon_1.3.4
[46] lattice_0.20-38         haven_2.1.0             splines_3.5.3
[49] hms_0.4.2               ps_1.3.0                pillar_1.3.1
[52] boot_1.3-20             pkgload_1.0.2           glue_1.3.1
[55] data.table_1.12.2       nloptr_1.2.1            testthat_2.0.1
[58] cellranger_1.1.0        RANN_2.6.1              gtable_0.3.0
[61] purrr_0.3.2             assertthat_0.2.1        openxlsx_4.1.0
[64] survey_3.35-1           e1071_1.7-1             rnaturalearth_0.1.0
[67] class_7.3-15            survival_2.43-3         tibble_2.1.1
[70] memoise_1.1.0           units_0.6-2
>

Ellen Yasumiishi, PhD (she/her/hers)
Research Fishery Biologist: 907-209-2819
NOAA Alaska Fisheries Science Center
17109 Point Lena Loop Road, Juneau, AK  99801

**Comment by James-Thorson-NOAA** [comment] 2021-04-06 16:00
Thanks as always for taking the time to point issues out!  

I can't replicate the problem using the [Wiki example](https://github.com/James-Thorson-NOAA/VAST/wiki/Visualize-covariate-response), so I'm having trouble speculating.  Could you try making a [minimal reproducible example](https://github.com/nwfsc-assess/geostatistical_delta-GLMM/wiki/How-to-create-a-minimal-example)

**Comment by EllenY** [comment] 2021-04-06 18:09
setwd("C:/Users/ellen.yasumiishi.vm/Documents/2020/2020Sockeye")
dat<-read.csv("IYSsockeyeCovariates18.csv") #2002-2018 Made up data for 2013, 2015, 2017, just matches 2012 data
#Includes dummy data for 2013, 2015, 2017 using 2012 data

print(dat)
head(dat)
tail(dat)
Year	=dat[,1]		#Survey year
Lat=dat[,2]			#Latitude in decimal degree
Lon=dat[,3]			#Longitude in decimal degree
SST	=dat[,4]		#Top 10 m sea temperature in Celsius
A0_Pollock	=dat[,5]	#Age-0 pollock catch (Kg)
J_Pink_Salmon=dat[,6]	#Juvenile pink salmon catch (kg)
Calanus	=dat[,7]	#Calanus copepod densities
AirT=dat[,8]			#Pacific Decadal Oscillation idex
HaulDate	=dat[,9]
StationID	=dat[,10]
AreaSwept=dat[,11]
Wt=dat[,12]

# load data set
SSTn<-scale(SST)
covariate_data = data.frame( "Lat"=dat[,'Lat'], "Lon"=dat[,'Lon'], "Year"=dat[,'Year'],"CPE"=(SSTn))

# Make settings (turning off bias.correct to save time for example)
settings = make_settings( n_x=100,Region="Other", purpose="index2" )

# Change Beta1 to AR1, to allow linear covariate effect
settings$RhoConfig['Beta1'] = 4

# Define formula.
X1_formula = ~ CPE
X2_formula = ~ 1
X1config_cp = array(3,dim=c(1,1))

# Run model
fit = fit_model( "settings" = settings,
  Lat_i = dat[,'Lat'],
  Lon_i = dat[,'Lon'],
       "observations_LL" = dat[,c('Lat','Lon')],
  t_i = dat[,'Year'],
  b_i = dat[,'Wt'],
  a_i = dat[,'AreaSwept'],
  X1_formula = X1_formula,
  X2_formula = X2_formula,
  X1config_cp = X1config_cp,
  covariate_data = covariate_data,
  test_fit = FALSE )


#ERROR 1.
### Writing output from `fit_model` in directory: C:/Users/ellen.yasumiishi.vm/Documents/2020/2020Sockeye/

### Making extrapolation-grid
For the UTM conversion, automatically detected zone 3.
# Reducing extrapolation-grid from 163200 to 2000 cells for Region(s): Other
n_x less than n_unique so no calculation necessary
Error in data.frame(..., check.names = FALSE) : 
  arguments imply differing number of rows: 866, 2000


#TRIED  adding settings$max_cells=Inf

#settings$max_cells=Inf
### Writing output from `fit_model` in directory: C:/Users/ellen.yasumiishi.vm/Documents/2020/2020Sockeye/

### Making extrapolation-grid
For the UTM conversion, automatically detected zone 3.

### Making spatial information
Loaded from C:/Users/ellen.yasumiishi.vm/Documents/2020/2020Sockeye//Kmeans-100.RData

### Making data object
Error in FishStatsUtils::make_covariates(formula = X1_formula, covariate_data = covariate_data,  : 
  unused argument (contrasts.arg = X_contrasts)

**Comment by EllenY** [comment] 2021-04-07 14:25
Do I need to install older versions of VAST and FishStatsUtils?

**Comment by James-Thorson-NOAA** [comment] 2021-04-07 14:31
Could you send me the data you sourced and I can try it out?

**Comment by EllenY** [comment] 2021-04-07 14:37
Sure thing, here it is.Wt is kg juvenile sockeye

Ellen Yasumiishi, PhD (she/her/hers)
Research Fishery Biologist: 907-209-2819
NOAA Alaska Fisheries Science Center
17109 Point Lena Loop Road, Juneau, AK  99801

**Comment by James-Thorson-NOAA** [comment] 2021-04-07 15:29
OK thanks!  

A minimal example of the error is:
```R
make_extrapolation_info("Region"="Other", "observations_LL" = cbind("Lat"=rnorm(100),"Lon"=rnorm(100)), "max_cells"=2000)
```
i.e., it appears to arise when using `Region = "Other"` and decreasing resolution.

One solution appears to be making your own explicit extrapolation-grid more carefully, e.g.
```R
make_extrapolation_info("Region"="User", "input_grid" = cbind("Lat"=rnorm(10000),"Lon"=rnorm(10000),"Area_km2"=1), "max_cells"=2000)
```
I think I remember making this suggestion for your study too;  would you consider just making your own input grid more [explicitly externally](https://github.com/James-Thorson-NOAA/VAST/wiki/Creating-an-extrapolation-grid) and I can then explore the bug without any fast timeline?

**Comment by EllenY** [comment] 2021-04-07 15:50
Do you want to create a "BASIS" survey Region using this dataset as a
default for VAST?
I will try making my own input grid using
https://github.com/James-Thorson-NOAA/VAST/wiki/Creating-an-extrapolation-grid
Thanks for sharing the link!



Ellen Yasumiishi, PhD (she/her/hers)
Research Fishery Biologist: 907-209-2819
NOAA Alaska Fisheries Science Center
17109 Point Lena Loop Road, Juneau, AK  99801

**Comment by James-Thorson-NOAA** [comment] 2021-04-07 15:53
Yeah, I think its worth having a BASIS grid!  But I don't know that taking the maximal extent (i.e., a polygon fitted to all stations that were ever sampled) is the best way.  Maybe its worth having three versions for different uses:
* maximal extent
* Core extent (pretty consistently sampled)
* some intermediate, like maximal extent after dropping stations that were sampled >=X times (like 3+ times)

**Comment by James-Thorson-NOAA** [comment] 2021-04-07 17:05
In other news ... I think I found the bug which arose when reducing the size (using `max_cells`) of an extrapolation-grid with a large proportion of cells with area=0.  I can only think of this arising when `Region = "Other"` and with a large padding for defining the area, relative to area for retaining samples.  The bug manifested in an uninformative error as you saw, so no previous user would have gotten mistaken results from the effect of this issue.  The bug is (I think) now fixed on dev branch.

closing for now, but feel free to re-post if the issue is not solved by re-installing from dev-branch of FishStatsUtils and VAST.

**Closed by James-Thorson-NOAA** 2021-04-07 17:05 UTC
