### ISSUE TITLE
7-Eleven

### ISSUE THREAD

**Issue by mintoc** [James-Thorson-NOAA/VAST#259] opened 2020-10-19 23:47 UTC
Hi Jim,

Any reason the `logsigmaM` parameter would be estimated when using `Obsmodel = c(7, 0)`, e.g.

```{r }
library(VAST)
set.seed(101)
n <- 20
xyz <- data.frame(year = 1, Lon = runif(n, -12, -5), Lat = runif(n, 48, 52))
m <- nrow(xyz)

xyz$z <- rpois(n, lambda = 2)


## Make settings
settings <- make_settings(n_x = 10,
                          Region = "other",
                          purpose = "index")
     
## Run zero-inflated Poisson 
fit0 <- fit_model(settings = settings,
                 Lat_i= xyz$Lat,
                 Lon_i = xyz$Lon,
                 t_i = xyz$year,
                 c_i = rep(0,nrow(xyz)),
                 b_i = xyz$z,
                 a_i = rep(1, nrow(xyz)),
                 observations_LL = xyz[,c('Lat','Lon')],
                 Obsmodel = c(7, 0),
                 Aniso = FALSE,
                 FieldConfig = c(Omega1 = 0, Epsilon1 = 0,
                                 Omega2 = 0, Epsilon2 = 0))

fit0$parameter_estimates$SD

sdreport(.) result
             Estimate Std. Error
beta1_ft   0.64033694  0.2805782
beta2_ft   0.06242476  0.2142985
logSigmaM -0.87593898  0.1714985
Maximum gradient component: 9.177571e-14 
```
I'd expect this additional normal variance parameter using  `Obsmodel = c(11, 0)` and I get the same results as above for that model:

```{r }
## Run zero-inflated Poisson with additional normal variation in rate
fit1 <- fit_model(settings = settings,
                  Lat_i= xyz$Lat,
                  Lon_i = xyz$Lon,
                  t_i = xyz$year,
                  c_i = rep(0,nrow(xyz)),
                  b_i = xyz$z,
                  a_i = rep(1, nrow(xyz)),
                  observations_LL = xyz[,c('Lat','Lon')],
                  Obsmodel = c(11, 0),
                  Aniso = FALSE,
                  FieldConfig = c(Omega1 = 0, Epsilon1 = 0,
                                  Omega2 = 0, Epsilon2 = 0))

fit1$parameter_estimates$SD

sdreport(.) result
             Estimate Std. Error
beta1_ft   0.64033694  0.2805782
beta2_ft   0.06242476  0.2142985
logSigmaM -0.87593898  0.1714985
Maximum gradient component: 9.177571e-14 

```
I checked the log likelihoods in the .cpp and they look good so i'm not sure where it's entering and why it would be there.
 
Using `VAST_v12_0_0` in R version 4.0.2 on Ubuntu 20.04

Many thanks,
Cóilín

**Comment by James-Thorson-NOAA** [comment] 2020-10-20 15:35
Cóilín,

Thanks for pointing it out, and providing such a clean and easily reproduced example!  I'm running it now, but based on your output it certainly seems like a bug in ObsModel[1] = 7 option (a normal Poisson distribution).  I imagine that I forgot to map off the overdispersion components from the lognormal-Poisson as you say, but I'll try to confirm and implement a hotfix if that turns out to be the case.

More (hopefully) soon

Jim

**Comment by James-Thorson-NOAA** [comment] 2020-10-20 15:49
OK, so it turned out to be a simple typo.  Please try:

```R
## Run zero-inflated Poisson 
fit0 <- fit_model(settings = settings,
                 Lat_i= xyz$Lat,
                 Lon_i = xyz$Lon,
                 t_i = xyz$year,
                 c_i = rep(0,nrow(xyz)),
                 b_i = xyz$z,
                 a_i = rep(1, nrow(xyz)),
                 observations_LL = xyz[,c('Lat','Lon')],
                 ObsModel = c(7, 0),
                 Aniso = FALSE,
                 FieldConfig = c(Omega1 = 0, Epsilon1 = 0,
                                 Omega2 = 0, Epsilon2 = 0))
```

where `Obsmodel` is now replaced with `ObsModel` (it was previously failing to match that input against the expected arguments of internal functions and therefore just ignoring it and defaulting to the `ObsModel` from `make_settings`, i.e., a Poisson-link delta-gamma distribution).  I also welcome any feedback on interface, including ways to make it easier to see how its parsing the user-defined inputs and defaults from `make_settings` to diagnose issues like this.

could you please close the issue if you can replicate my fix?

**Comment by mintoc** [comment] 2020-10-20 21:23
Hi Jim,

My bad and sincere apologies for wasting your time with a typo!

Your solution works but I then run into two things

1) I get an error

```{r}
Error in par[] <- x : replacement has length zero
```
caused by line 220 [here](https://github.com/James-Thorson-NOAA/FishStatsUtils/blob/82cd3b5e07baa92d182c0746558575e0be597e52/R/fit_model.R#L220) looking for `parameter_estimates$par` instead of `parameter_estimates$opt$par`. 

2) The parameter estimates and warning about the hessian are very different to running this model elsewhere:

```{r}
library(pscl)
fit0_pscl <- zeroinfl(z ~ 1, data = xyz, dist = "poisson")
```

In terms of the interface, we've found it very useful. To diagnose my error more easily, dropping a default using something like

```{r}
        if (missing(ObsModel)){
            ## ObsModel = c(2, 1) ## current
            stop("argument 'ObsModel' is missing, with no default")
        }
```
Though that could cause many issues for default models up and running.

Cheers,
Cóilín

**Comment by James-Thorson-NOAA** [comment] 2020-10-21 00:46
Coilin,

Thanks for flagging topic-1 above.  Hopefully I'll find time to fix that :0

Regarding topic-2 above, I've added a [new integrated-test](https://github.com/James-Thorson-NOAA/VAST/blob/development/tests/testthat/test-zeroinfl-against-pscl.R) comparing the intercept-only VAST model for the zero-inflated Poisson against the `pscl::zeroinf` implementation; thanks for suggesting this and providing the simulation and estimation code to adapt!  It seems to be matching the output there (both in MLE and SE calculations), but of course I welcome another set of eyes.  

I'm closing for now but happy to keep commenting here.

**Closed by James-Thorson-NOAA** 2020-10-21 00:46 UTC

**Comment by mintoc** [comment] 2020-10-21 08:14
Hi Jim,

That's great and the test works well. Many thanks for incredible help. 

Cheers,
Cóilín
