### ISSUE TITLE
SE of EOF factor loadings 

### ISSUE THREAD

**Issue by slarge** [James-Thorson-NOAA/VAST#365] opened 2023-02-20 19:49 UTC
I'm not finding the `results$Factors$Rotated_loadings_SE` as expected running the example EOF3. Any suggestions?

```
### Load packages
library(VAST)

### load data set
example = load_example( data_set="five_species_ordination" )

### Make settings:
### including modifications from default settings to match 
### analysis in original paper
settings = make_settings( n_x=50,
                          Region=example$Region,
                          purpose="EOF3",
                          n_categories=2,
                          ObsModel=c(1,1),
                          RhoConfig=c("Beta1"=0,"Beta2"=0,"Epsilon1"=0,"Epsilon2"=0) )

### Run model (including settings to speed up run)
fit = fit_model( settings=settings,
                 Lat_i=example$sampling_data[,'Lat'],
                 Lon_i=example$sampling_data[,'Lon'],
                 t_i=example$sampling_data[,'Year'],
                 c_i=example$sampling_data[,'species_number']-1,
                 b_i=example$sampling_data[,'Catch_KG'],
                 a_i=example$sampling_data[,'AreaSwept_km2'],
                 newtonsteps=0,
                 getsd=TRUE, ## Note: the example has this FALSE
                 Use_REML=TRUE )

### Plot results, including spatial term Omega1
results = plot( fit,
                check_residuals=FALSE,
                plot_set=c(3,16),
                category_names = c("pollock", "cod", "arrowtooth", "snow_crab", "yellowfin") )

str(results$Factors)

List of 5
 $ Loadings                 :List of 8
  ..$ Omega1      : chr "Element not estimated, and therefore empty"
  ..$ Epsilon1    : chr "Element not estimated, and therefore empty"
  ..$ Beta1       : chr "Element not estimated, and therefore empty"
  ..$ EpsilonTime1: num [1:34, 1:2] 0.614 0.866 0.413 0.538 0.294 ...
  .. ..- attr(*, "dimnames")=List of 2
  .. .. ..$ Time: chr [1:34] "1982" "1983" "1984" "1985" ...
  .. .. ..$     : NULL
  ..$ Omega2      : chr "Element not estimated, and therefore empty"
  ..$ Epsilon2    : chr "Element not estimated, and therefore empty"
  ..$ Beta2       : chr "Element not estimated, and therefore empty"
  ..$ EpsilonTime2: chr "Element not estimated, and therefore empty"
 $ Rotated_loadings         :List of 8
  ..$ Omega1      : chr "Element not estimated, and therefore empty"
  ..$ Epsilon1    : chr "Element not estimated, and therefore empty"
  ..$ Beta1       : chr "Element not estimated, and therefore empty"
  ..$ EpsilonTime1: num [1:34, 1:2] -0.587 -0.871 -0.612 -0.642 -0.449 ...
  .. ..- attr(*, "dimnames")=List of 2
  .. .. ..$ : chr [1:34] "1982" "1983" "1984" "1985" ...
  .. .. ..$ : NULL
  ..$ Omega2      : chr "Element not estimated, and therefore empty"
  ..$ Epsilon2    : chr "Element not estimated, and therefore empty"
  ..$ Beta2       : chr "Element not estimated, and therefore empty"
  ..$ EpsilonTime2: chr "Element not estimated, and therefore empty"
 $ Rotated_factors          :List of 8
  ..$ Omega1      : chr "Element not estimated, and therefore empty"
  ..$ Epsilon1    : chr "Element not estimated, and therefore empty"
  ..$ Beta1       : chr "Element not estimated, and therefore empty"
  ..$ EpsilonTime1: num [1:102, 1:5, 1:2] -0.189 -0.725 -0.949 -1.114 -1.541 ...
  ..$ Omega2      : chr "Element not estimated, and therefore empty"
  ..$ Epsilon2    : chr "Element not estimated, and therefore empty"
  ..$ Beta2       : chr "Element not estimated, and therefore empty"
  ..$ EpsilonTime2: chr "Element not estimated, and therefore empty"
 $ Rotated_projected_factors:List of 8
  ..$ Omega1      : chr "Element not estimated, and therefore empty"
  ..$ Epsilon1    : chr "Element not estimated, and therefore empty"
  ..$ Beta1       : chr "Element not estimated, and therefore empty"
  ..$ EpsilonTime1: num [1:2000, 1:5, 1:2] 0.0152 -0.2981 0.7985 -0.0507 -0.5113 ...
  ..$ Omega2      : chr "Element not estimated, and therefore empty"
  ..$ Epsilon2    : chr "Element not estimated, and therefore empty"
  ..$ Beta2       : chr "Element not estimated, and therefore empty"
  ..$ EpsilonTime2: chr "Element not estimated, and therefore empty"
 $ Rotation_matrices        :List of 8
  ..$ Omega1      : chr "Element not estimated, and therefore empty"
  ..$ Epsilon1    : chr "Element not estimated, and therefore empty"
  ..$ Beta1       : chr "Element not estimated, and therefore empty"
  ..$ EpsilonTime1:List of 1
  .. ..$ rotmat: num [1:2, 1:2] 0.956 0.293 0.293 -0.956
  ..$ Omega2      : chr "Element not estimated, and therefore empty"
  ..$ Epsilon2    : chr "Element not estimated, and therefore empty"
  ..$ Beta2       : chr "Element not estimated, and therefore empty"
  ..$ EpsilonTime2: chr "Element not estimated, and therefore empty" 

> sessionInfo()
R version 4.2.2 (2022-10-31)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 22.04.1 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/openblas-pthread/libblas.so.3
LAPACK: /usr/lib/x86_64-linux-gnu/openblas-pthread/libopenblasp-r0.3.20.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8       
 [4] LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                  LC_ADDRESS=C              
[10] LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] VAST_3.10.1           FishStatsUtils_2.12.1 marginaleffects_0.9.0 units_0.8-1          
[5] TMB_1.9.2             ggplot2_3.4.0         tidyr_1.3.0           dplyr_1.1.0          

loaded via a namespace (and not attached):
 [1] fastcluster_1.2.3       shape_1.4.6             tidyselect_1.2.0       
 [4] reshape2_1.4.4          purrr_1.0.1             sf_1.0-9               
 [7] splines_4.2.2           lattice_0.20-45         rnaturalearth_0.3.2    
[10] colorspace_2.1-0        vctrs_0.5.2             generics_0.1.3         
[13] viridisLite_0.4.1       s2_1.1.2                utf8_1.2.2             
[16] rlang_1.0.6             e1071_1.7-12            pillar_1.8.1           
[19] glue_1.6.2              withr_2.5.0             DBI_1.1.3              
[22] TMBhelper_1.4.0         sp_1.6-0                wk_0.7.1               
[25] plyr_1.8.8              lifecycle_1.0.3         stringr_1.5.0          
[28] munsell_0.5.0           gtable_0.3.1            parallel_4.2.2         
[31] class_7.3-20            fansi_1.0.4             Rcpp_1.0.10            
[34] corpcor_1.6.10          KernSmooth_2.23-20      INLA_22.12.16          
[37] scales_1.2.1            classInt_0.4-8          plotrix_3.8-2          
[40] jsonlite_1.8.4          abind_1.4-5             RANN_2.6.1             
[43] stringi_1.7.12          ecodist_2.0.9           splancs_2.01-43        
[46] ThorsonUtilities_1.0    grid_4.2.2              rprojroot_2.0.3        
[49] here_1.0.1              rgdal_1.6-4             cli_3.6.0              
[52] tools_4.2.2             magrittr_2.0.3          proxy_0.4-27           
[55] tibble_3.1.8            pkgconfig_2.0.3         Matrix_1.5-1           
[58] data.table_1.14.6       httr_1.4.4              rstudioapi_0.14        
[61] R6_2.5.1                rnaturalearthdata_0.1.0 compiler_4.2.2    

```

**Comment by James-Thorson-NOAA** [comment] 2023-02-20 22:30
Thanks for flagging this!  I just made a push to FishStatsUtils `main` branch (and also brought the change over to the new `dev` branch) which should fix this.  The issue was my misunderstanding of default behavior in `is.missing`, which was not detecting the `sdreport` inputs even though it was being passed.

Anyhoo, are you willing to try updating via `remotes::install_github("james-thorson-NOAA/FishStatsUtils", force=TRUE)` and see if the problem is resolved?  Or feel free to just make a local copy of `plot_factors` and run that individually.

I'm closing for now, but please tell me if the problem persists, or confirm if it is solved.

**Closed by James-Thorson-NOAA** 2023-02-20 22:30 UTC

**Comment by James-Thorson-NOAA** [comment] 2023-02-20 23:14
I'm working on this low-key today and sorry for extra messages ... I found another small edit required, and added that only to the `dev` branch of FishStatsUtils, so if testing please use that
