### ISSUE TITLE
plot of fits now fails with "TMBconfig" not available for .Call() for package "VAST_v13_0_0"

### ISSUE THREAD

**Issue by smormede** [James-Thorson-NOAA/VAST#315] opened 2021-12-16 22:33 UTC
Hello,

I have an error message that has appeared within the last few weeks. I haven't updated R or packages or changed anything I am doing. 

I run VAST models using the function 'fit_model'
I then plot the results using the call: plot(fit,plot_set=3)

I now get the following error in the plotting:

### Making plot of anisotropy
Skipping plot of geometric anisotropy because it has been turned off
### Making plot of abundance index
Using bias-corrected estimates for abundance index (natural-scale)...
Not using bias-corrected estimates for abundance index (log-scale)...
### Making plot of spatial indices
Plotting center-of-gravity...
Not using bias-corrected estimates for center of gravity...
Plotting effective area occupied...
Not using bias-corrected estimates for effective area occupied (natural scale)...
Not using bias-corrected estimates for effective area occupied (log scale)...
### Making plot of range edges
Error in .Call("TMBconfig", e, as.integer(1), PACKAGE = DLL) : 
  "TMBconfig" not available for .Call() for package "VAST_v13_0_0"

Any idea? Is anyone having the same issue? This worked until at least early November 2021 but doesn't anymore. 

Thanks

Sophie

**Comment by jindivero** [comment] 2022-02-17 18:23
Hi Sophie,
I just started getting the same error. Were you ever able to find a solution?
Thanks!
Julia

**Comment by CacciapagliaC** [comment] 2022-02-17 18:55
I've had a couple of similar errors, including one involving "Matrix" not available for .Call() for package "VAST_v...". Here is an error I just recreated below,

#Making plot of anisotropy
Error in .Call("TMBconfig", e, as.integer(1), PACKAGE = DLL) : 
  "TMBconfig" not available for .Call() for package "VAST_v13_1_0"

For me it seems to happen when my R session crashes and I reload the '.Rdata' file that included my VAST model fit from the session that crashed.  After reloading the data and packages, when I use any VAST affiliated function, I get similar errors. I've been able to remedy it by re-running the original model fit 'fit_model()'  before using whatever function I am trying to run. What helped lead me to that workaround was when running 'simulate_data()' after a crash, the output was:

Error in simulate_data(fit_orig, type = Type, random_seed = SEED[rI]) : 
  VAST is not linked as a DLL, so `simulate_data` will not work.
    Please re-run model (potentially from informative starting values to save time) to use `simulate_data`
 
I went into a dive looking into the DLL - dynamic library loading, and it seems to maybe have some connection to where the packages load, then it went into compiling information and package creation which is above me. My best guess is that it has something to do with this being a package loaded through Github, and for some reason how (or where) it is saved doesn't allow a perfect transfer between various sessions and uploaded data. Hopefully this helps you, and I am also interested in what the outcome from this issue is.  

Best,
Chris

**Comment by smormede** [comment] 2022-02-18 19:37
Thanks both. I haven't found how to fix this, I'm at the hands of more experts people than me. My issue seems different from Chris': my R session doesn't crash and I do the plots immediately after running the model.

**Comment by James-Thorson-NOAA** [comment] 2022-02-23 00:51
@CacciapagliaC As you said, some functions called during plotting (i.e., range-edges and DHARMa diagnostics) require a fully linked and fitted model.  So a few options:

1. running all plots after the fit;
2. re-running `fit_model` if necessary; or
3. or turning off sample-based calculations using `fit_model( ..., n_samples=0)`

I'd also welcome help making an auto-function in `FishStatsUtils` to take a fit and re-link the DLL, but currently don't know how to do it. 

@jindivero feel free to chime in here if that fixes things for you.  

@smormede  The error you show seems like it would be caused by this as well.   Please email me if the problem persists, or give more details here.

I'm closing for now, but happy to re-open after hearing more from you @smormede

**Closed by James-Thorson-NOAA** 2022-02-23 00:51 UTC

**Comment by smormede** [comment] 2022-03-01 19:03
Hello @James-Thorson-NOAA 

I have tried the following:
1. running the plots after the fits - I now get this error: 
### Making plot of range edges
Error in registerFinalizer(Fun, DLL) : 
could not find function "registerFinalizer"

I get it too when I rerun the plots which have worked in the past. This is now a different error from when this was posted initially.

2. re-running fit_model - same error

3. using fit_model(...,n_samples=0) I get the following error 
Error in inDL(x, as.logical(local), as.logical(now), ...) :  Unknown external ptr type

I have no idea why things are changing like that.

Thanks

Sophie

**Comment by smormede** [comment] 2022-08-29 21:08
Hello. Just an update for those still struggling with this issue. If I rerun the model in the same folder I get the error, but if I rerun the model in a new folder then I don't. It might help trouble-shoot too. thanks.
