### ISSUE TITLE
Query about the definition of dPoisGam likelihood in VAST_v12_0_0.cpp

### ISSUE THREAD

**Issue by joenomiddlename** [James-Thorson-NOAA/VAST#260] opened 2020-10-29 23:48 UTC
Hi!

First of all I'd like to say a HUGE thanks for providing and developing such awesome software!

I am thinking about implementing the Compound Poisson Gamma likelihood in VAST. After reading the foster and Bravington (2012) paper, they define the log-likelihood in equation (6) very similarly to you, however the sign of the first term (written "-x/scale" in your code) is positive in their paper. The rest of the set-up looks identical to the paper.

Thus it appears that the sign is incorrect in the VAST code. Please could you double-check the sign? 

Best,
Joe

**Comment by James-Thorson-NOAA** [comment] 2020-10-30 18:35
Thanks for checking it!  

I emailed with Scott Foster and Mark Bravington, and told them about that typo in their Eq. 6.  They then confirmed that it was a typo.  So I'm reasonably confident that the code in VAST is correct.

Could you respond with more details about your intended use of the compound Poisson-gamma implementation in VAST?  On the development branch I was actually eliminating it because I don't have a simple quantile or random-number generator (which are now used in VAST for different forms of diagnostics).  I'd be happy to reconsider retaining it, but would love help on writing and validating the rPoisGam function needed.

**Comment by joenomiddlename** [comment] 2020-10-30 20:36
Thanks for the speedy response! Ah - great catch :) This puts the equation in VAST in line with the result in: https://www.hindawi.com/journals/jps/2018/1012647/

With regards to the compound Poisson-gamma implementation in VAST, I have a really nice data set with one or more of the following available at a large set of locations and times: counts, total biomass and the masses of individuals. Thus a joint integrative model for combining all three within one framework seemed a fun idea! Given the link between the compound Poisson-gamma and Tweedie distributions, should I just use the dtweedie likelihood instead with the correct parameterization? I have heard (informally) that the dtweedie can be a little numerically unstable. What do you think? Note that I am modifying the VAST cpp files anyway, so I have extra flexibility with regards to data structure and parameterization and do not need to rigorously stick to the VAST structure.

**Comment by James-Thorson-NOAA** [comment] 2020-10-30 21:39
Sounds great!  I'm not aware of any study separately doing total biomass and biomass of individuals;  FWIW we've previously explored presence/absence (an implied complementary log-log link), counts (Poisson) and biomass (Poisson link delta model as computational approximation to compound Poisson-gamma) here: https://academic.oup.com/icesjms/article-abstract/76/6/1748/5479986

The dtweedie in TMB is very fast and stable in my experience as long as there's only random effects in the mean-parameter, and theta and p are both constant or a function of fixed effects.  It then becomes *very* slow when trying to treat theta as a loglinear function of random effects.  This is feasible via reductions in VAST using the ObsModel = c(10,2) specification in case you want to read the short description in `?make_data`.  I remember the Foster-Bravington formula for compound Poisson-gamma also being infeasible with spatial variables estimated, but can't remember if I explored a reduced model with spatial variation in the log-linear predictor for only one of the two processes.

I'm closing for now but feel free to continue posting here or email me to discuss as you progress!

**Closed by James-Thorson-NOAA** 2020-10-30 21:39 UTC

**Comment by joenomiddlename** [comment] 2020-10-30 22:55
Thanks so much again for your speedy response! I really appreciate your help :) The `Poisson link' idea in your paper https://cdnsciencepub.com/doi/10.1139/cjfas-2017-0266 has been the inspiration behind my models.

Thanks for the tips regarding the dtweedie function. I'll keep you posted on my progress!
